import React, { useState } from 'react';
import {
  StyleSheet, View, Text, ScrollView, TouchableOpacity,
  ActivityIndicator, Share, Alert,
} from 'react-native';
import { FontAwesome, MaterialIcons, AntDesign, Ionicons } from '@expo/vector-icons';
import { RootStackScreenProps, MeetingRecord, Participant } from '../types';
import { MeetingStore } from '../store/meetingStore';

// ─── Local MoM Generator ─────────────────────────────────────────────────────
// Generates a professional Minutes of Meeting document entirely on-device.
// Parses the notes for action items, decisions, and discussion points.
function generateMoMLocally(meeting: MeetingRecord): string {
  const date = MeetingStore.formatDate(meeting.startTime);
  const startTime = MeetingStore.formatTime(meeting.startTime);
  const endTime = meeting.endTime ? MeetingStore.formatTime(meeting.endTime) : 'N/A';
  const duration = meeting.endTime
    ? MeetingStore.formatDuration(meeting.endTime - meeting.startTime)
    : 'N/A';

  const attendeeLines = meeting.participants
    .map((p, i) => {
      const dur = p.leaveTime
        ? MeetingStore.formatDuration(p.leaveTime - p.joinTime)
        : duration;
      const role = i === 0 ? ' (Host)' : '';
      return `  • ${p.name}${role} — attended ${dur}`;
    })
    .join('\n');

  // Parse notes into structured sections
  const rawNotes = (meeting.notes || '').trim();
  const noteLines = rawNotes ? rawNotes.split('\n').filter(l => l.trim()) : [];

  const actionItems: string[] = [];
  const decisions: string[] = [];
  const discussionPoints: string[] = [];
  const otherNotes: string[] = [];

  noteLines.forEach(line => {
    const l = line.toLowerCase();
    if (l.includes('action') || l.includes('todo') || l.includes('to do') || l.includes('follow up') || l.includes('task')) {
      actionItems.push(line.trim());
    } else if (l.includes('decided') || l.includes('decision') || l.includes('agreed') || l.includes('approved') || l.includes('resolved')) {
      decisions.push(line.trim());
    } else if (l.includes('discuss') || l.includes('review') || l.includes('present') || l.includes('cover')) {
      discussionPoints.push(line.trim());
    } else if (line.trim().startsWith('-') || line.trim().startsWith('•') || line.trim().startsWith('*')) {
      discussionPoints.push(line.trim());
    } else if (line.trim()) {
      otherNotes.push(line.trim());
    }
  });

  // Generate discussion points from topic if none captured
  if (discussionPoints.length === 0 && otherNotes.length === 0) {
    discussionPoints.push(
      `  • Meeting opened by ${meeting.hostName} regarding: ${meeting.topic}`,
      `  • Participants reviewed the agenda and key objectives`,
      `  • Open discussion was held among all attendees`,
      `  • Meeting concluded with alignment on next steps`
    );
  }

  // Build formatted MoM
  const hr = '─'.repeat(42);
  let mom = '';

  mom += `MINUTES OF MEETING\n${hr}\n\n`;

  mom += `MEETING DETAILS\n`;
  mom += `Topic      : ${meeting.topic}\n`;
  mom += `Host       : ${meeting.hostName}\n`;
  mom += `Date       : ${date}\n`;
  mom += `Start Time : ${startTime}\n`;
  mom += `End Time   : ${endTime}\n`;
  mom += `Duration   : ${duration}\n`;
  mom += `Room ID    : ${meeting.roomId}\n\n`;

  mom += `ATTENDEES (${meeting.participants.length})\n${hr}\n`;
  mom += `${attendeeLines}\n\n`;

  mom += `DISCUSSION POINTS\n${hr}\n`;
  if (discussionPoints.length > 0) {
    discussionPoints.forEach(p => { mom += `${p.startsWith('•') || p.startsWith('-') || p.startsWith(' ') ? p : '  • ' + p}\n`; });
  } else if (otherNotes.length > 0) {
    otherNotes.slice(0, 5).forEach(n => { mom += `  • ${n}\n`; });
  } else {
    mom += `  • General discussion as per the agenda\n`;
  }
  mom += '\n';

  if (decisions.length > 0) {
    mom += `DECISIONS MADE\n${hr}\n`;
    decisions.forEach(d => { mom += `  ✓ ${d.replace(/^[-•*]\s*/, '')}\n`; });
    mom += '\n';
  }

  if (actionItems.length > 0) {
    mom += `ACTION ITEMS\n${hr}\n`;
    actionItems.forEach(a => { mom += `  → ${a.replace(/^[-•*]\s*/, '')}\n`; });
    mom += '\n';
  }

  if (otherNotes.length > 0 && (discussionPoints.length > 0 || rawNotes)) {
    mom += `ADDITIONAL NOTES\n${hr}\n`;
    otherNotes.forEach(n => { mom += `  ${n}\n`; });
    mom += '\n';
  }

  mom += `NEXT STEPS\n${hr}\n`;
  if (actionItems.length > 0) {
    mom += `  • Complete all action items listed above\n`;
  }
  mom += `  • Circulate this MoM to all participants\n`;
  mom += `  • Schedule follow-up meeting if required\n\n`;

  mom += `${hr}\n`;
  mom += `Generated by Confero on ${date} at ${MeetingStore.formatTime(Date.now())}`;

  return mom;
}

// ─── Attendance Row ───────────────────────────────────────────────────────────
function AttendanceRow({ p, index, meetingStart, meetingEnd }: {
  p: Participant; index: number; meetingStart: number; meetingEnd?: number;
}) {
  const joinedAt = MeetingStore.formatTime(p.joinTime);
  const leftAt = p.leaveTime ? MeetingStore.formatTime(p.leaveTime) : 'End of call';
  const durationMs = p.leaveTime
    ? p.leaveTime - p.joinTime
    : (meetingEnd ?? Date.now()) - p.joinTime;
  const duration = MeetingStore.formatDuration(durationMs);
  const totalMs = (meetingEnd ?? Date.now()) - meetingStart;
  const pct = totalMs > 0 ? Math.round((durationMs / totalMs) * 100) : 100;
  const lateMs = p.joinTime - meetingStart;
  const isLate = lateMs > 90000; // more than 90 seconds late

  return (
    <View style={styles.attRow}>
      <View style={[styles.attAvatar, { backgroundColor: AVATAR_COLORS[index % AVATAR_COLORS.length] }]}>
        <Text style={styles.attInitial}>{p.name.charAt(0).toUpperCase()}</Text>
      </View>
      <View style={styles.attInfo}>
        <View style={styles.attNameRow}>
          <Text style={styles.attName} numberOfLines={1}>{p.name}</Text>
          {index === 0 && <View style={styles.hostBadge}><Text style={styles.hostText}>Host</Text></View>}
          {isLate && <View style={styles.lateBadge}><Text style={styles.lateText}>Late</Text></View>}
        </View>
        <Text style={styles.attTime}>
          {joinedAt} → {leftAt}
        </Text>
        {/* Attendance bar */}
        <View style={styles.attBarBg}>
          <View style={[styles.attBarFill, { width: `${Math.min(pct, 100)}%` as any }]} />
        </View>
        <Text style={styles.attPct}>{pct}% attended</Text>
      </View>
      <View style={styles.attDurBox}>
        <Text style={styles.attDur}>{duration}</Text>
      </View>
    </View>
  );
}

const AVATAR_COLORS = ['#4f6ef7', '#2ecc71', '#e67e22', '#9b59b6', '#e74c3c', '#1abc9c'];

// ─── Main Screen ──────────────────────────────────────────────────────────────
export default function MeetingSummaryScreen({
  route, navigation,
}: RootStackScreenProps<'MeetingSummary'>) {
  const { meeting } = route.params;
  const [mom, setMom] = useState('');
  const [generatingMom, setGeneratingMom] = useState(false);

  const totalDuration = meeting.endTime
    ? MeetingStore.formatDuration(meeting.endTime - meeting.startTime)
    : '—';

  const handleGenerateMoM = () => {
    setGeneratingMom(true);
    // Small timeout so UI shows spinner (generation is synchronous but fast)
    setTimeout(() => {
      const result = generateMoMLocally(meeting);
      setMom(result);
      setGeneratingMom(false);
    }, 600);
  };

  const shareReport = async () => {
    let text = mom || generateMoMLocally(meeting);
    await Share.share({
      message: text,
      title: `${meeting.topic} — Confero MoM`,
    });
  };

  // Average attendance percentage
  const totalMs = meeting.endTime
    ? meeting.endTime - meeting.startTime
    : Date.now() - meeting.startTime;
  const avgAttendance = meeting.participants.length > 0
    ? Math.round(
        meeting.participants.reduce((sum, p) => {
          const dur = (p.leaveTime ?? meeting.endTime ?? Date.now()) - p.joinTime;
          return sum + Math.min((dur / totalMs) * 100, 100);
        }, 0) / meeting.participants.length
      )
    : 100;

  return (
    <ScrollView style={styles.wrapper} contentContainerStyle={styles.content}>
      {/* Header */}
      <View style={styles.header}>
        <AntDesign name="checkcircle" size={56} color="#2ecc71" />
        <Text style={styles.headerTitle}>Meeting Ended</Text>
        <Text style={styles.headerTopic}>{meeting.topic}</Text>
      </View>

      {/* Stats Row */}
      <View style={styles.statsRow}>
        <View style={styles.statBox}>
          <Text style={styles.statVal}>{totalDuration}</Text>
          <Text style={styles.statLbl}>Duration</Text>
        </View>
        <View style={[styles.statBox, styles.statMid]}>
          <Text style={styles.statVal}>{meeting.participants.length}</Text>
          <Text style={styles.statLbl}>Attendees</Text>
        </View>
        <View style={styles.statBox}>
          <Text style={styles.statVal}>{avgAttendance}%</Text>
          <Text style={styles.statLbl}>Avg Attendance</Text>
        </View>
      </View>

      {/* Meeting info */}
      <View style={styles.infoCard}>
        {[
          { icon: 'user' as const, label: 'Host', value: meeting.hostName },
          { icon: 'calendar' as const, label: 'Date', value: MeetingStore.formatDate(meeting.startTime) },
          { icon: 'clock-o' as const, label: 'Time', value: `${MeetingStore.formatTime(meeting.startTime)} – ${meeting.endTime ? MeetingStore.formatTime(meeting.endTime) : '?'}` },
          { icon: 'key' as const, label: 'Room ID', value: meeting.roomId },
        ].map(({ icon, label, value }) => (
          <View key={label} style={styles.infoRow}>
            <FontAwesome name={icon} size={13} color="#4f6ef7" />
            <Text style={styles.infoLabel}>{label}</Text>
            <Text style={styles.infoValue} numberOfLines={1}>{value}</Text>
          </View>
        ))}
      </View>

      {/* Attendance Report */}
      <View style={styles.section}>
        <View style={styles.sectionHeader}>
          <Ionicons name="people" size={17} color="#4f6ef7" />
          <Text style={styles.sectionTitle}>Attendance Report</Text>
        </View>
        {meeting.participants.map((p, i) => (
          <AttendanceRow
            key={i} p={p} index={i}
            meetingStart={meeting.startTime}
            meetingEnd={meeting.endTime}
          />
        ))}
      </View>

      {/* Notes */}
      {!!meeting.notes && (
        <View style={styles.section}>
          <View style={styles.sectionHeader}>
            <FontAwesome name="pencil" size={15} color="#4f6ef7" />
            <Text style={styles.sectionTitle}>Notes</Text>
          </View>
          <View style={styles.notesBox}>
            <Text style={styles.notesText}>{meeting.notes}</Text>
          </View>
        </View>
      )}

      {/* MoM Section */}
      <View style={styles.section}>
        <View style={styles.sectionHeader}>
          <MaterialIcons name="description" size={17} color="#a78bfa" />
          <Text style={[styles.sectionTitle, { color: '#a78bfa' }]}>Minutes of Meeting</Text>
        </View>
        <Text style={styles.momHint}>
          Generate a professional MoM document based on your meeting details and notes.
        </Text>

        {!mom && !generatingMom && (
          <TouchableOpacity style={styles.generateBtn} onPress={handleGenerateMoM}>
            <MaterialIcons name="auto-fix-high" size={18} color="#a78bfa" />
            <Text style={styles.generateText}>Generate MoM</Text>
          </TouchableOpacity>
        )}

        {generatingMom && (
          <View style={styles.loadingBox}>
            <ActivityIndicator color="#a78bfa" size="small" />
            <Text style={styles.loadingText}>Generating your MoM…</Text>
          </View>
        )}

        {!!mom && (
          <View style={styles.momBox}>
            <Text style={styles.momText}>{mom}</Text>
            <TouchableOpacity style={styles.regenBtn} onPress={handleGenerateMoM}>
              <AntDesign name="reload1" size={13} color="#a78bfa" />
              <Text style={styles.regenText}>Regenerate</Text>
            </TouchableOpacity>
          </View>
        )}
      </View>

      {/* Action Buttons */}
      <TouchableOpacity style={styles.shareBtn} onPress={shareReport}>
        <MaterialIcons name="share" size={18} color="#fff" />
        <Text style={styles.shareBtnText}>Share Full Report</Text>
      </TouchableOpacity>

      <TouchableOpacity
        style={styles.historyBtn}
        onPress={() => navigation.navigate('MeetingHistory')}>
        <FontAwesome name="history" size={16} color="#4f6ef7" />
        <Text style={styles.historyBtnText}>View Meeting History</Text>
      </TouchableOpacity>

      <TouchableOpacity style={styles.homeBtn} onPress={() => navigation.navigate('Home')}>
        <Text style={styles.homeBtnText}>Back to Home</Text>
      </TouchableOpacity>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  wrapper: { backgroundColor: '#0a0a0f', flex: 1 },
  content: { paddingHorizontal: 20, paddingTop: 24, paddingBottom: 50 },
  header: { alignItems: 'center', marginBottom: 22 },
  headerTitle: { color: '#fff', fontSize: 22, fontWeight: 'bold', marginTop: 14, marginBottom: 4 },
  headerTopic: { color: '#555', fontSize: 15 },
  statsRow: {
    flexDirection: 'row', backgroundColor: '#13132a',
    borderRadius: 16, marginBottom: 16,
    borderWidth: 1, borderColor: '#1e1e3f', overflow: 'hidden',
  },
  statBox: { flex: 1, alignItems: 'center', paddingVertical: 16 },
  statMid: { borderLeftWidth: 1, borderRightWidth: 1, borderColor: '#1e1e3f' },
  statVal: { color: '#fff', fontSize: 18, fontWeight: 'bold' },
  statLbl: { color: '#555', fontSize: 11, marginTop: 3 },
  infoCard: {
    backgroundColor: '#13132a', borderRadius: 14, padding: 14,
    marginBottom: 18, borderWidth: 1, borderColor: '#1e1e3f',
  },
  infoRow: {
    flexDirection: 'row', alignItems: 'center',
    paddingVertical: 9, borderBottomWidth: 1, borderBottomColor: '#1a1a2e', gap: 10,
  },
  infoLabel: { color: '#555', fontSize: 13, width: 58 },
  infoValue: { color: '#ccc', fontSize: 13, flex: 1, textAlign: 'right' },
  section: { marginBottom: 22 },
  sectionHeader: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 12 },
  sectionTitle: { color: '#fff', fontSize: 15, fontWeight: 'bold' },
  attRow: {
    flexDirection: 'row', alignItems: 'center',
    backgroundColor: '#13132a', borderRadius: 12, padding: 12,
    marginBottom: 8, borderWidth: 1, borderColor: '#1e1e3f',
  },
  attAvatar: {
    width: 42, height: 42, borderRadius: 21,
    justifyContent: 'center', alignItems: 'center', marginRight: 12, flexShrink: 0,
  },
  attInitial: { color: '#fff', fontSize: 17, fontWeight: 'bold' },
  attInfo: { flex: 1 },
  attNameRow: { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: 2 },
  attName: { color: '#fff', fontSize: 14, fontWeight: '600', flexShrink: 1 },
  hostBadge: {
    backgroundColor: '#4f6ef733', borderRadius: 4, paddingHorizontal: 6, paddingVertical: 1,
  },
  hostText: { color: '#4f6ef7', fontSize: 10, fontWeight: '700' },
  lateBadge: {
    backgroundColor: '#c0392b22', borderRadius: 4, paddingHorizontal: 6, paddingVertical: 1,
  },
  lateText: { color: '#e74c3c', fontSize: 10, fontWeight: '700' },
  attTime: { color: '#555', fontSize: 11, marginBottom: 6 },
  attBarBg: {
    height: 4, backgroundColor: '#1e1e3f', borderRadius: 2, marginBottom: 3,
  },
  attBarFill: { height: 4, backgroundColor: '#4f6ef7', borderRadius: 2 },
  attPct: { color: '#444', fontSize: 10 },
  attDurBox: { marginLeft: 10, alignItems: 'flex-end' },
  attDur: { color: '#4f6ef7', fontSize: 14, fontWeight: 'bold' },
  notesBox: {
    backgroundColor: '#13132a', borderRadius: 12, padding: 14,
    borderWidth: 1, borderColor: '#1e1e3f',
  },
  notesText: { color: '#aaa', fontSize: 13, lineHeight: 21 },
  momHint: { color: '#444', fontSize: 13, lineHeight: 18, marginBottom: 14 },
  generateBtn: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'center',
    borderRadius: 12, paddingVertical: 14, gap: 8,
    backgroundColor: '#1e1040', borderWidth: 1, borderColor: '#4f3aaa',
  },
  generateText: { color: '#a78bfa', fontSize: 15, fontWeight: 'bold' },
  loadingBox: {
    flexDirection: 'row', alignItems: 'center', gap: 12,
    backgroundColor: '#13132a', borderRadius: 12, padding: 16,
  },
  loadingText: { color: '#a78bfa', fontSize: 14 },
  momBox: {
    backgroundColor: '#13132a', borderRadius: 12, padding: 16,
    borderWidth: 1, borderColor: '#2d1f5e',
  },
  momText: { color: '#ccc', fontSize: 12, lineHeight: 20, fontFamily: 'SpaceMono' } as any,
  regenBtn: {
    flexDirection: 'row', alignItems: 'center', gap: 6,
    marginTop: 14, alignSelf: 'flex-end',
  },
  regenText: { color: '#a78bfa', fontSize: 12 },
  shareBtn: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'center',
    backgroundColor: '#4f6ef7', borderRadius: 14, paddingVertical: 15,
    gap: 10, marginBottom: 12,
  },
  shareBtnText: { color: '#fff', fontSize: 16, fontWeight: 'bold' },
  historyBtn: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'center',
    borderRadius: 14, paddingVertical: 14, gap: 8, marginBottom: 12,
    borderWidth: 1, borderColor: '#1e1e3f',
  },
  historyBtnText: { color: '#4f6ef7', fontSize: 15, fontWeight: '600' },
  homeBtn: {
    alignItems: 'center', paddingVertical: 14,
    borderRadius: 14, borderWidth: 1, borderColor: '#1a1a2e',
  },
  homeBtnText: { color: '#444', fontSize: 15 },
});
